AdoteUmPet/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('home.urls')),
    path('animal/', include('animal.urls')),
    path('perfil/', include('perfil.urls')),
    path('admin/', admin.site.urls),
]

animal/urls.py
from django.urls import path
from animal.views import AnimalDetalhe

app_name = 'pet'

urlpatterns = [
    path('detalhe/<slug:slug>', AnimalDetalhe.as_view(), name='detalhe')
]

home/urls.py
from django.urls import path
from .views import HomePesquisa, HomeView

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('pesquisa', HomePesquisa.as_view(), name='pesquisa')
]

perfil/urls.py
from django.urls import path

from perfil.views import teste_view

app_name = 'perfil'

urlpatterns = [
    path('<str:nome>', teste_view.as_view(), name='detalhe'),

]

animal/models.py
from django.db import models
from perfil.models import Perfil
from django.utils.text import slugify

# Create your models here.
class Especie(models.Model):
    nome = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.nome
    

class Raca(models.Model):
    nome = models.CharField(max_length=50, blank=False, null=False)
    especie = models.OneToOneField(to=Especie, on_delete=models.CASCADE, blank=False, null=False)

    def __str__(self):
        return self.nome


class Animal(models.Model):
    nome = models.CharField(max_length=255, blank=False, null=False)
    idade = models.IntegerField()
    local = models.CharField(max_length=255)
    doador = models.ForeignKey(Perfil, on_delete=models.CASCADE, blank=False, null=False)
    especie = models.ForeignKey(Especie, on_delete=models.DO_NOTHING, blank=False, null=False)
    raca = models.ForeignKey(Raca, on_delete=models.DO_NOTHING, blank=True, null=True)
    descricao = models.TextField()
    slug = models.SlugField(verbose_name='Slug', blank=True, null=True)

    def __str__(self):
        return self.nome

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.nome)

        return super().save()
        

home/models.py
from django.db import models

# Create your models here.

perfil/models.py
from configparser import MAX_INTERPOLATION_DEPTH
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.
class Perfil(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE, blank=False, null=False)
    username = models.CharField(max_length=100, blank=False, null=False)
    first_name = models.CharField(max_length=100, blank=False, null=False, verbose_name='Primeiro Nome')
    last_name = models.CharField(max_length=100, blank=False, null=False, verbose_name='Sobrenome')
    email = models.EmailField(verbose_name='E-mail', blank=False, null=False)
    password = models.CharField(max_length=255, blank=False, null=False)
    slug = models.SlugField(verbose_name='Slug')

    def save(self, *args, **kwargs):
       super(Perfil, self).save(*args, **kwargs) # Call the real save() method
       if not self.slug:
           self.slug = slugify(self.username)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

animal/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from .models import Animal

# Create your views here.

class AnimalDetalhe(DetailView):
    template_name = 'animal/detalhe.html'
    model = Animal

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)

        animal = self.get_object()

        detalhes = Animal.objects.get(slug=animal.slug)

        contexto['animal'] = animal

        return contexto

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, UpdateView
from animal.models import Animal

# Create your views here.
class HomeView(ListView):
    template_name = 'home/home.html'
    context_object_name = 'animais'
    model = Animal

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        animais = Animal.objects.all()

        context['animais'] = animais

        return context

class HomePesquisa(TemplateView):
    pass

perfil/views.py
from django.shortcuts import render
from django.views.generic import DetailView

# Create your views here.
class teste_view(DetailView):
    pass

animal/templates/animal/detalhe.html
{% extends 'base.html' %}

{% block 'conteudo' %}

<p>{{animal.nome}}</p>

<a href="{% url 'perfil:detalhe' animal.doador_id %}"><p>{{animal.doador}}</p></a>

<p>{{animal.idade}} anos</p>

<p>{{animal.descricao}}</p>


{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}


{% block 'conteudo' %}
  <div class="row mx-auto">
    {% for animal in animais %}
        <div class="col-*-* p-3 pt-5 pd-5 border border-2 m-4" style='width: 250px'>
          <a href="{% url 'pet:detalhe' animal.slug %}"><h3 class="mx-auto">{{animal.nome}}</h3></a>
          <h4 class="mx-auto">{{animal.idade}} anos</h4>
          <h4 class="mx-auto">{{animal.raca}}</h4>
          <a href="#"><h6 class="mx-auto">Doador: {{animal.doador}}</h6></a>
        </div>
        
    {% endfor %}
  </div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
    <body>
        {% include 'partials/_nav.html' %}
        
        {% block 'conteudo' %}

            Esta é a Base

        {% endblock %}

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    </body>

</html>

templates/partials/_nav.html
<nav class='navbar navbar-expand-sm bg-light border border-bottom'>
    <div class='container-fluid d-flex justify-content-between pt-2'>
        <img src="srcs/logo.png" alt='Logo' width='48' height='48'>
        <ul class='navbar-nav'>
            <li class='nav-item pr-2'>
                <a href="{% url 'home:home' %}"><h6>Home</h6></a>
            </li>
            <li class='nav-item pr-2'>
                <a href="{% url 'home:pesquisa' %}"><h6>Pesquisar Pet</h6></a>
            </li>
            <li class='nav-item pr-2'>
                <h6>Terceiro Link</h6>
            </li>

        </ul>

    </div>
</nav>